# Generated by Django 5.2.11 on 2026-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
