# Generated by Django 5.2.11 on 2026-04-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
        ('surveillance', '0006_targetperson_uploaded_by_detectionevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='camera.camera'),
        ),
    ]
