# Generated by Django 5.2.11 on 2026-04-11 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0007_detectionevent_camera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='related_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='surveillance.targetassignment'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='verification_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='surveillance.detectionevent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'New Assignment'), ('pass_back', 'Passed Back to You'), ('detection', 'Target Detected'), ('verification', 'Verification Required'), ('approved', 'Detection Approved'), ('rejected', 'Detection Rejected'), ('system', 'System Alert')], default='system', max_length=20),
        ),
    ]
