# Generated by Django 5.2.11 on 2026-04-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0008_detectionevent_related_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'New Assignment'), ('pass_back', 'Passed Back to You'), ('detection', 'Target Detected'), ('verification', 'Verification Required'), ('approved', 'Detection Approved'), ('rejected', 'Detection Rejected'), ('system', 'System Alert'), ('assignment', 'New Assignment'), ('pass_back', 'Passed Back to You'), ('detection', 'Target Detected'), ('system', 'System Alert')], default='system', max_length=20),
        ),
    ]
